name: size

on:
  pull_request:
    branches: [main]

jobs:
  size:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/action-setup@v6
      - uses: actions/setup-node@v7
        with:
          node-version-file: ".nvmrc"
          cache: pnpm

      - name: Run dist
        run: pnpm build

      - run: pnpm install --frozen-lockfile

      - name: Run size-limit
        run: pnpm size
